### ISSUE TITLE
ref is not HTML

### ISSUE THREAD

**Issue by elmimmo** [thomaspark/pubcss#1]
The `ref` element as mentioned in <http://thomaspark.me/2015/01/pubcss-formatting-academic-publications-in-html-css/> is not a valid HTML element. Such element exists in neither http://developers.whatwg.org nor http://www.w3.org/TR/html5/ nor http://www.w3.org/TR/html51/

You cannot call it HTML if it is not HTML.

**Comment by MattiSG** [comment]
Yes, these should be `<cite>`.

**Comment by elmimmo** [comment]
Indeed, @MattiSG. But an added issue is that PubCSS' required markup already does use `cite` for another purpose, and one which is seemingly not valid HTML just as well.

> Citations to the references make use of these IDs.
> 
>     <cite href="#nicole"></cite>

The `cite` element is not intended to be a way of linking (you have the `a` element for that) but, as @MattiSG pointed out, to cite (i.e. to mention, to reference) titles of works (and authors of such works, if you prefer [W3C's version of `cite`](http://www.w3.org/TR/html5/text-level-semantics.html#the-cite-element) to [WHATWG's version of `cite`](https://developers.whatwg.org/text-level-semantics.html#the-cite-element)).

In other words, in no HTML specification can `cite` have an `href` attribute, so PubCSS' use of it is not valid HTML too.

I think @thomaspark is mixing two different scenarios:

1.	Linking to tables and figures. This can be done with regular `id` attributes in `table` and `figure` and and a standard internal HTML link like `<a href="#…">…</a>`.

2.	Providing a list of creative works at the end of the document, and referencing them in short form from within the main body of the text.

	Each title of a work in the list of works at the end should be wrapped with <cite id="…">…</cite>.

	The references to them from within the main body might be wrapped in <cite>…</cite> (no `id` needed, unless one wants to be able to link back to the reference in some other place) only if their short form is still descriptive enough to differentiate what work it is, and then, the whole thing should be wrapped again with a standard internal HTML link like `<a href="#…">…</a>` pointing to the `id` of the referenced work at the end.

At any rate, and even if @thomaspark fixed PubCSS' non-valid uses of HTML (which he should IMHO), pretending that non-web people will write in HTML straight is wishful thinking (and bad advice) IMHO. Tools such as [Pandoc](https://github.com/jgm/pandoc) can provide those people with a nice balance between being able to comfortably write technical papers without creativity or thinking process being hindered by the syntax and obtaining nicely structured documents with standard rich HTML.

I think PubCSS should be doing good if it expected HTML markup to be like that output by Pandoc (which, at any rate, should be good HTML markup even for those that care not one bit about producing their source with Pandoc's version of Markdown).

**Comment by MattiSG** [comment]
Thanks for these very precise and relevant details, @elmimmo  :)

Let's try to separate concerns about the product’s use-cases and HTML standards compliance, though.

I think @elmimmo gave the solution: `<cite id="work">` + `<a href="#work"><cite>` is probably the way it should be. Admittedly, this is less concise than the current format, but being compliant means it will be much, much easier to interoperate with other tools, and I’d expect PubCSS to do so to become a common format.
With an HTML-compliant spec, for example, one could simply use a `cite` extension for Markdown and decrease the barrier to entry  :)

**Comment by thomaspark** [comment]
@elmimmo, thanks for opening this and the other issues. I think they cover all of the cases of invalid HTML, which I'll iron out (nb: the CSS is another matter).

Along with validation, the markup should ideally be concise and obvious. The proposed seems like a good solution in all regards.

**Comment by MattiSG** [comment]
Nice, congrats!  :)
