### ISSUE TITLE
MathJax CDN will soon be shut down.

### ISSUE THREAD

**Issue by cbleslie** [thomaspark/pubcss#11]
[As the MathJax blog post has stated](https://www.mathjax.org/cdn-shutting-down/), the CDN will be closing: April 30, 2017.  They have/will provide alternate CDN's for people to use as stated in the above blogpost.

**Comment by thomaspark** [comment]
@cbleslie, thanks for the heads up. Demos have been updated to cdnjs.

http://thomaspark.co/project/pubcss/demo/acm-sig-sample-web.html
http://thomaspark.co/project/pubcss/demo/acm-sig-sample-web-theme.html
