### ISSUE TITLE
broken linkes 

### ISSUE THREAD

**Issue by ahmad88me** [thomaspark/pubcss#15]
https://github.com/thomaspark/pubcss/blob/master/dist/acm-sig/templates/ieee-sample.pdf
https://github.com/thomaspark/pubcss/blob/master/dist/acm-sig/templates/acm-sigchi-ea-sample.pdf
https://github.com/thomaspark/pubcss/blob/master/dist/acm-sig/templates/acm-sigchi-sample.pdf

**Comment by thomaspark** [comment]
Fixed, thanks.

**Comment by ahmad88me** [comment]
Thanks for the fast fix 👍
